from enum import StrEnum


class Gebruiksdoel(StrEnum):
    WOONFUNCTIE = "WOON"
    BIJEENKOMSTFUNCTIE = "B"
    CELFUNCTIE = "C"
    GEZONDHEIDSZORGFUNCTIE = "G"
    INDUSTRIEFUNCTIE = "I"
    KANTOORFUNCTIE = "K"
    LOGIESFUNCTIE = "L"
    ONDERWIJSFUNCTIE = "O"
    SPORTFUNCTIE = "S"
    WINKELFUNCTIE = "WINK"
    OVERIGE_GEBRUIKSFUNCTIE = "O"


class Type(StrEnum):
    VERBLIJFSOBJECT = "V"
    STANDPLAATS = "S"
    LIGPLAATS = "L"


class Status(StrEnum):
    BOUWVERGUNNING_VERLEEND = "BV"
    NIET_GEREALISEERD_PAND = "NG"
    BOUW_GESTART = "BG"
    PAND_IN_GEBRUIK_NIET_INGEMETEN = "PGN"
    PAND_IN_GEBRUIK = "PIG"
    VERBOUWING_PAND = "VP"
    SLOOPVERGUNNING_VERLEEND = "SV"
    PAND_GESLOOPT = "PG"
    PAND_BUITEN_GEBRUIK = "PB"
    PAND_TEN_ONRECHTE_OPGEVOERD = "PO"
